### ISSUE TITLE
Training weight file

### ISSUE THREAD

**Issue by applepingping** [yjzhang96/NeurMAP-deblur#4]
Hello, I feel the wonderful idea you put forward, I am very interested in your work, I want to train on my own unpaired data set, I noticed that these are not provided in the configuration file, can you provide me? Thank you!
![WechatIMG1060](https://github.com/yjzhang96/NeurMAP-deblur/assets/142369705/f7252be7-5667-4162-bbe3-a6e071694f50)

**Comment by yjzhang96** [comment]
Sorry for the late reply. There are some pretrained weight files not provided in the README description. For your convenience, I have uploaded these files and updated README correspondingly. Hope it can help you continue your own work.

**Comment by applepingping** [comment]
Thanks a lot！
